# Generated by Django 2.1.4 on 2018-12-10 02:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysanitation', '0003_resturant_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='resturants',
        ),
        migrations.AddField(
            model_name='profile',
            name='restaurants_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), null=True, size=None),
        ),
    ]
