version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 8000:80
    environment:
      - NGINX_PORT=80
    volumes:
      - ./load_balancer/logs:/etc/nginx/logs/
      - ./load_balancer/nginx.conf:/etc/nginx/nginx.conf
    tty: true
    depends_on:
      - web1
      - web2
      - memcached
  memcached:
    container_name: memcached
    image: memcached:latest
  web1:
    build: 
      context: ./src
      dockerfile: ./Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    working_dir: /code/src
    ports:
      - 8001:8000
    volumes:
      - .:/code
    depends_on:
      - memcached
  web2:
    build: 
      context: ./src
      dockerfile: ./Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    working_dir: /code/src
    ports:
      - 8002:8000
    volumes:
      - .:/code
    depends_on:
      - memcached