version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 8001:80
    environment:
      - NGINX_PORT=80
    volumes:
      - ./load_balancer/nginx.conf:/etc/nginx/nginx.conf
    command: ["nginx", "-g", "daemon off;"]
    tty: true
    depends_on:
      - web
      - memcached
  memcached:
    container_name: memcached
    image: memcached:latest
  web:
    build: ./src
    command: python3 manage.py runserver 0.0.0.0:8000
    working_dir: /code/src
    volumes:
      - .:/code