# Generated by Django 2.1.4 on 2018-12-10 02:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysanitation', '0004_auto_20181210_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='restaurants_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
