# Generated by Django 2.1.4 on 2018-12-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysanitation', '0005_auto_20181210_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resturant',
            name='violation',
        ),
        migrations.AddField(
            model_name='resturant',
            name='address',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
