# Generated by Django 2.1.4 on 2018-12-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysanitation', '0006_auto_20181210_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturant',
            name='zipcode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
